#!/bin/sh
# $FreeBSD$
# PROVIDE: dragonfly-mle
# REQUIRE: DAEMON
# BEFORE: LOGIN
# KEYWORD: shutdown
# Add the following lines to /etc/rc.conf to enable dragonfly:
#
# dragonfly_enable (bool):   Set to YES to enable dragonfly
#                            Default: NO
#
# --------------------------------------------------------------
. /etc/rc.subr
name="dragonfly-mle"
rcvar=${name}_enable
load_rc_config $name
: ${dragonfly_enable:="NO"}
: ${dragonfly_root:="usr/local/${name}"}
# daemon
start_precmd=dragonfly_prestart
command=/usr/sbin/daemon
pidfile="/var/run/${name}"
command_args="-rfP ${pidfile} /usr/local/${name}/${name} -r ${dragonfly_root}"
dragonfly_prestart() {
# Have to empty rc_flags so they don't get passed to daemon(8)
    rc_flags=""
}
run_rc_command "$1"

